window:
  padding:
    x: 6 
    y: 6 

  decorations: none 

  title: Console
  dynamic_title: true

  opacity: 0.95

font:
  normal:
    family: SauceCodePro Nerd Font Mono
    style: regular
  bold:
    family: SauceCodePro Nerd Font Mono
    style: bold
  italic:  
    family: SauceCodePro Nerd Font Mono
    style: italic
  size: 8.0
  draw_bold_text_with_bright_colors: true

# THEMES

# Define
schemes:
  everforest_dark_hard: &everforest_dark_hard
    primary:
      background: '#1E2326'
      foreground: '#d3c6aa'
    normal:
      black:   '#414b50'
      red:     '#e67e80'
      green:   '#a7c080'
      yellow:  '#dbbc7f'
      blue:    '#7fbbb3'
      magenta: '#d699b6'
      cyan:    '#83c092'
      white:   '#d3c6aa'
    bright:
      black:   '#475258'
      red:     '#e67e80'
      green:   '#a7c080'
      yellow:  '#dbbc7f'
      blue:    '#7fbbb3'
      magenta: '#d699b6'
      cyan:    '#83c092'
      white:   '#d3c6aa'
  everforest_dark_medium: &everforest_dark_medium
    primary:
      background: '#2d353b'
      foreground: '#d3c6aa'
    normal:
      black:   '#475258'
      red:     '#e67e80'
      green:   '#a7c080'
      yellow:  '#dbbc7f'
      blue:    '#7fbbb3'
      magenta: '#d699b6'
      cyan:    '#83c092'
      white:   '#d3c6aa'
    bright:
      black:   '#475258'
      red:     '#e67e80'
      green:   '#a7c080'
      yellow:  '#dbbc7f'
      blue:    '#7fbbb3'
      magenta: '#d699b6'
      cyan:    '#83c092'
      white:   '#d3c6aa'
  everforest_dark_soft: &everforest_dark_soft
    primary:
      background: '#333c43'
      foreground: '#d3c6aa'
    normal:
      black:   '#4d5960'
      red:     '#e67e80'
      green:   '#a7c080'
      yellow:  '#dbbc7f'
      blue:    '#7fbbb3'
      magenta: '#d699b6'
      cyan:    '#83c092'
      white:   '#d3c6aa'
    bright:
      black:   '#4d5960'
      red:     '#e67e80'
      green:   '#a7c080'
      yellow:  '#dbbc7f'
      blue:    '#7fbbb3'
      magenta: '#d699b6'
      cyan:    '#83c092'
      white:   '#d3c6aa'
  everforest_light_hard: &everforest_light_hard
    primary:
      background: '#fffbef'
      foreground: '#5c6a72'
    normal:
      black:   '#5c6a72'
      red:     '#f85552'
      green:   '#8da101'
      yellow:  '#dfa000'
      blue:    '#3a94c5'
      magenta: '#df69ba'
      cyan:    '#35a77c'
      white:   '#e8e5d5'
    bright:
      black:   '#5c6a72'
      red:     '#f85552'
      green:   '#8da101'
      yellow:  '#dfa000'
      blue:    '#3a94c5'
      magenta: '#df69ba'
      cyan:    '#35a77c'
      white:   '#e8e5d5'
  everforest_light_medium: &everforest_light_medium
    primary:
      background: '#fdf6e3'
      foreground: '#5c6a72'
    normal:
      black:   '#5c6a72'
      red:     '#f85552'
      green:   '#8da101'
      yellow:  '#dfa000'
      blue:    '#3a94c5'
      magenta: '#df69ba'
      cyan:    '#35a77c'
      white:   '#e0dcc7'
    bright:
      black:   '#5c6a72'
      red:     '#f85552'
      green:   '#8da101'
      yellow:  '#dfa000'
      blue:    '#3a94c5'
      magenta: '#df69ba'
      cyan:    '#35a77c'
      white:   '#e0dcc7'
  everforest_light_soft: &everforest_light_soft
    primary:
      background: '#f3ead3'
      foreground: '#5c6a72'
    normal:
      black:   '#5c6a72'
      red:     '#f85552'
      green:   '#8da101'
      yellow:  '#dfa000'
      blue:    '#3a94c5'
      magenta: '#df69ba'
      cyan:    '#35a77c'
      white:   '#d8d3ba'
    bright:
      black:   '#5c6a72'
      red:     '#f85552'
      green:   '#8da101'
      yellow:  '#dfa000'
      blue:    '#3a94c5'
      magenta: '#df69ba'
      cyan:    '#35a77c'
      white:   '#d8d3ba'
  nord: &nord
    primary:
      background: "#2e3440"
      foreground: "#d8dee9"
      dim_foreground: "#a5abb6"
    cursor:
      text: "#2e3440"
      cursor: "#d8dee9"
    vi_mode_cursor:
      text: "#2e3440"
      cursor: "#d8dee9"
    selection:
      text: CellForeground
      background: "#4c566a"
    search:
      matches:
        foreground: CellBackground
        background: "#88c0d0"
      footer_bar:
        background: "#434c5e"
        foreground: "#d8dee9"
    normal:
      black: "#3b4252"
      red: "#bf616a"
      green: "#a3be8c"
      yellow: "#ebcb8b"
      blue: "#81a1c1"
      magenta: "#b48ead"
      cyan: "#88c0d0"
      white: "#e5e9f0"
    bright:
      black: "#4c566a"
      red: "#bf616a"
      green: "#a3be8c"
      yellow: "#ebcb8b"
      blue: "#81a1c1"
      magenta: "#b48ead"
      cyan: "#8fbcbb"
      white: "#eceff4"
    dim:
      black: "#373e4d"
      red: "#94545d"
      green: "#809575"
      yellow: "#b29e75"
      blue: "#68809a"
      magenta: "#8c738c"
      cyan: "#6d96a5"
      white: "#aeb3bb"
  dracula: &dracula
    primary:
      background: '#282a36'
      foreground: '#f8f8f2'
      bright_foreground: '#ffffff'
    cursor:
      text: CellBackground
      cursor: CellForeground
    vi_mode_cursor:
      text: CellBackground
      cursor: CellForeground
    search:
      matches:
        foreground: '#44475a'
        background: '#50fa7b'
      focused_match:
        foreground: '#44475a'
        background: '#ffb86c'
    footer_bar:
      background: '#282a36'
      foreground: '#f8f8f2'
    hints:
      start:
        foreground: '#282a36'
        background: '#f1fa8c'
      end:
        foreground: '#f1fa8c'
        background: '#282a36'
    line_indicator:
      foreground: None
      background: None
    selection:
      text: CellForeground
      background: '#44475a'
    normal:
      black: '#21222c'
      red: '#ff5555'
      green: '#50fa7b'
      yellow: '#f1fa8c'
      blue: '#bd93f9'
      magenta: '#ff79c6'
      cyan: '#8be9fd'
      white: '#f8f8f2'
    bright:
      black: '#6272a4'
      red: '#ff6e6e'
      green: '#69ff94'
      yellow: '#ffffa5'
      blue: '#d6acff'
      magenta: '#ff92df'
      cyan: '#a4ffff'
      white: '#ffffff'


# Apply
colors: *everforest_dark_hard
